---

- name: installed version
  command: >
    php -v
  register: php_installed_version
  ignore_errors: yes

- name: print version
  debug: >
    msg="Available PHP version: {{ php_installed_version.stdout_lines[0] }} -- Wanted: {{ php_version }}"
  ignore_errors: yes

- name: download tarball
  get_url: >
    url="http://museum.php.net/php5/php-{{ php_version }}.tar.gz"
    dest="{{ php_install_tmp }}/php-{{ php_version }}.tar.gz"
    validate_certs=no
  when: 
    
- name: unarchive package
  unarchive: >
    src="{{ php_install_tmp }}/php-{{ php_version }}.tar.gz"
    dest="{{ php_install_tmp }}"
    creates="{{ php_install_tmp }}/php-{{ php_version }}"
    copy=no
    
- name: configure
  command: >
    ./configure --prefix=/opt
    chdir="{{ php_install_tmp }}/php-{{ php_version }}"
  
- name: make
  command: >
    make
    chdir="{{ php_install_tmp }}/php-{{ php_version }}"

- name: make install
  command: >
    make install
    chdir="{{ php_install_tmp }}/php-{{ php_version }}"

- name: compiled version
  command: >
    php -v
  register: php_compiled_version

- name: print version
  debug: >
    msg="Ansible compiled PHP version: {{ php_compiled_version.stdout_lines[0] }} -- Wanted: {{ php_version }}"



